name: hris_frontend-prod

services:
  hris_frontend-prod:
    container_name: hris_frontend-prod 
    build:
      context: ../../
      dockerfile: docker/production/Dockerfile
    image: hoshigakikisame/hris_frontend-prod:latest
    ports:
      - "80:3000"
    deploy:
      resources:
        limits:
          memory: 512m
    networks:
      - hris_frontend-prod

  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower
    restart: unless-stopped
    command: --cleanup --interval 30 --include-stopped
    environment:
      - WATCHTOWER_CLEANUP=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - hris_frontend-prod

    
networks:
  hris_frontend-prod: