services:
  with-docker-multi-env-production:
    build:
      context: ../../
      dockerfile: docker/production/Dockerfile
    image: with-docker-multi-env-production
    ports:
      - "3002:3000"
    deploy:
      resources:
        limits:
          memory: 512m